config/routes.rb
Afiper::Engine.routes.draw do
  resources :contribuyentes
end

app/models/afiper/application_record.rb
# frozen_string_literal: true

module Afiper
  # Modelo base
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/afiper/comprobante.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: afiper_comprobantes
#
#  id                        :bigint           not null, primary key
#  afiper_contribuyente_id   :bigint           not null
#  comprobante_asociado_id   :bigint
#  tipo                      :integer          not null
#  fecha                     :date             not null
#  punto_de_venta            :integer          not null
#  numero                    :integer          not null
#  emisor_inicio_actividades :date             not null
#  emisor_cuit               :string           not null
#  emisor_iibb               :string           not null
#  emisor_razon_social       :string           not null
#  receptor_doc_tipo         :integer          not null
#  receptor_doc_nro          :string           not null
#  receptor_razon_social     :string           not null
#  receptor_condicion_iva    :integer          not null
#  condicion_venta           :integer          not null
#  receptor_codigo_pais      :bigint
#  receptor_cuit_pais        :bigint
#  receptor_domicilio        :string
#  exportacion_id_impositivo :string
#  concepto                  :integer          not null
#  moneda                    :integer          default("pesos"), not null
#  moneda_cotizacion         :float            default(1.0), not null
#  fecha_servicio_desde      :date
#  fecha_servicio_hasta      :date
#  fecha_vencimiento_pago    :date
#  creado_por_el_sistema     :boolean          not null
#  fiscal                    :boolean          not null
#  cae                       :string
#  vencimiento_cae           :date
#  afip_result               :string
#  deleted_at                :datetime
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#

require 'afiper/application_record'

module Afiper
  # Comprobante de pago, puede ser fiscal o no fiscal
  class Comprobante < ApplicationRecord
    extend Enumerize

    class << self
      def configuracion_tipos
        [
          { id: 1,  nombre: :factura_a,            descripcion: 'Factura A',                                      codigo_afip: 1,    nombre_print: 'FACTURA',                                              letra: 'A', exportacion: false, multiplicador_saldo:  1, tiene_iva: true,  adicionar_iva: false, mostrar_iva: true,  recibo: false },
          { id: 2,  nombre: :factura_b,            descripcion: 'Factura B',                                      codigo_afip: 6,    nombre_print: 'FACTURA',                                              letra: 'B', exportacion: false, multiplicador_saldo:  1, tiene_iva: true,  adicionar_iva: false, mostrar_iva: false, recibo: false },
          { id: 3,  nombre: :factura_c,            descripcion: 'Factura C',                                      codigo_afip: 11,   nombre_print: 'FACTURA',                                              letra: 'C', exportacion: false, multiplicador_saldo:  1, tiene_iva: false, adicionar_iva: false, mostrar_iva: false, recibo: false },
          { id: 4,  nombre: :nota_de_credito_a,    descripcion: 'Nota de crédito A',                              codigo_afip: 3,    nombre_print: 'NOTA DE CREDITO',                                      letra: 'A', exportacion: false, multiplicador_saldo: -1, tiene_iva: true,  adicionar_iva: false, mostrar_iva: true,  recibo: false },
          { id: 5,  nombre: :nota_de_credito_b,    descripcion: 'Nota de crédito B',                              codigo_afip: 8,    nombre_print: 'NOTA DE CREDITO',                                      letra: 'B', exportacion: false, multiplicador_saldo: -1, tiene_iva: true,  adicionar_iva: false, mostrar_iva: false, recibo: false },
          { id: 6,  nombre: :nota_de_credito_c,    descripcion: 'Nota de crédito C',                              codigo_afip: 13,   nombre_print: 'NOTA DE CREDITO',                                      letra: 'C', exportacion: false, multiplicador_saldo: -1, tiene_iva: false, adicionar_iva: false, mostrar_iva: false, recibo: false },
          { id: 7,  nombre: :nota_de_debito_a,     descripcion: 'Nota de débito A',                               codigo_afip: 2,    nombre_print: 'NOTA DE DEBITO',                                       letra: 'A', exportacion: false, multiplicador_saldo:  1, tiene_iva: true,  adicionar_iva: false, mostrar_iva: true,  recibo: false },
          { id: 8,  nombre: :nota_de_debito_b,     descripcion: 'Nota de débito B',                               codigo_afip: 7,    nombre_print: 'NOTA DE DEBITO',                                       letra: 'B', exportacion: false, multiplicador_saldo:  1, tiene_iva: true,  adicionar_iva: false, mostrar_iva: false, recibo: false },
          { id: 9,  nombre: :nota_de_debito_c,     descripcion: 'Nota de débito C',                               codigo_afip: 12,   nombre_print: 'NOTA DE DEBITO',                                       letra: 'C', exportacion: false, multiplicador_saldo:  1, tiene_iva: false, adicionar_iva: false, mostrar_iva: false, recibo: false },
          { id: 10, nombre: :recibo_a,             descripcion: 'Recibo A',                                       codigo_afip: 4,    nombre_print: 'RECIBO',                                               letra: 'A', exportacion: false, multiplicador_saldo:  0, tiene_iva: true,  adicionar_iva: false, mostrar_iva: false, recibo: true  },
          { id: 11, nombre: :recibo_b,             descripcion: 'Recibo B',                                       codigo_afip: 9,    nombre_print: 'RECIBO',                                               letra: 'B', exportacion: false, multiplicador_saldo:  0, tiene_iva: true,  adicionar_iva: false, mostrar_iva: false, recibo: true  },
          { id: 12, nombre: :ticket_no_fiscal,     descripcion: I18n.t('tipo_comprobante.ticket_no_fiscal'),      codigo_afip: nil,  nombre_print: I18n.t('tipo_comprobante.ticket_no_fiscal_print'),      letra: 'X', exportacion: false, multiplicador_saldo:  1, tiene_iva: false, adicionar_iva: false, mostrar_iva: false, recibo: false },
          { id: 13, nombre: :devolucion_no_fiscal, descripcion: I18n.t('tipo_comprobante.devolucion_no_fiscal'),  codigo_afip: nil,  nombre_print: I18n.t('tipo_comprobante.devolucion_no_fiscal_print'),  letra: 'X', exportacion: false, multiplicador_saldo: -1, tiene_iva: false, adicionar_iva: false, mostrar_iva: false, recibo: false },
          { id: 14, nombre: :factura_e,            descripcion: 'Factura E',                                      codigo_afip: 19,   nombre_print: 'FACTURA',                                              letra: 'E', exportacion: true,  multiplicador_saldo:  1, tiene_iva: false, adicionar_iva: false, mostrar_iva: false, recibo: false },
          { id: 15, nombre: :nota_de_debito_e,     descripcion: 'Nota de débito E',                               codigo_afip: 20,   nombre_print: 'NOTA DE DEBITO',                                       letra: 'E', exportacion: true,  multiplicador_saldo:  1, tiene_iva: false, adicionar_iva: false, mostrar_iva: false, recibo: false },
          { id: 16, nombre: :nota_de_credito_e,    descripcion: 'Nota de crédito E',                              codigo_afip: 21,   nombre_print: 'NOTA DE CREDITO',                                      letra: 'E', exportacion: true,  multiplicador_saldo: -1, tiene_iva: false, adicionar_iva: false, mostrar_iva: false, recibo: false }
        ]
      end

      def configuracion_doc_tipos
        [
          { id: 1,  nombre: :cuit,                      descripcion: 'CUIT',                    codigo_afip: '80' },
          { id: 2,  nombre: :cuil,                      descripcion: 'CUIL',                    codigo_afip: '86' },
          { id: 3,  nombre: :cdi,                       descripcion: 'CDI',                     codigo_afip: '87' },
          { id: 4,  nombre: :le,                        descripcion: 'LE',                      codigo_afip: '89' },
          { id: 5,  nombre: :lc,                        descripcion: 'LC',                      codigo_afip: '90' },
          { id: 6,  nombre: :ci_extranjera,             descripcion: 'CI Extranjera',           codigo_afip: '91' },
          { id: 7,  nombre: :en_tramite,                descripcion: 'en trámite',              codigo_afip: '92' },
          { id: 8,  nombre: :acta_nacimiento,           descripcion: 'Acta Nacimiento',         codigo_afip: '93' },
          { id: 9,  nombre: :ci_bs_as_rnp,              descripcion: 'CI Bs. As. RNP',          codigo_afip: '95' },
          { id: 10, nombre: :dni,                       descripcion: 'DNI',                     codigo_afip: '96' },
          { id: 11, nombre: :pasaporte,                 descripcion: 'Pasaporte',               codigo_afip: '94' },
          { id: 12, nombre: :ci_policia_federal,        descripcion: 'CI Policía Federal',      codigo_afip: '0'  },
          { id: 13, nombre: :ci_buenos_aires,           descripcion: 'CI Buenos Aires',         codigo_afip: '1'  },
          { id: 14, nombre: :ci_catamarca,              descripcion: 'CI Catamarca',            codigo_afip: '2'  },
          { id: 15, nombre: :ci_cordoba,                descripcion: 'CI Córdoba',              codigo_afip: '3'  },
          { id: 16, nombre: :ci_corrientes,             descripcion: 'CI Corrientes',           codigo_afip: '4'  },
          { id: 17, nombre: :ci_entre_rios,             descripcion: 'CI Entre Ríos',           codigo_afip: '5'  },
          { id: 18, nombre: :ci_jujuy,                  descripcion: 'CI Jujuy',                codigo_afip: '6'  },
          { id: 19, nombre: :ci_mendoza,                descripcion: 'CI Mendoza',              codigo_afip: '7'  },
          { id: 20, nombre: :ci_la_rioja,               descripcion: 'CI La Rioja',             codigo_afip: '8'  },
          { id: 21, nombre: :ci_salta,                  descripcion: 'CI Salta',                codigo_afip: '9'  },

app/models/afiper/contribuyente.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: afiper_contribuyentes
#
#  id                            :bigint           not null, primary key
#  razon_social                  :string           not null
#  cuit                          :string           not null
#  iibb                          :string           not null
#  inicio_actividades            :date             not null
#  condicion_iva                 :integer          not null
#  domicilio                     :string           not null
#  afip_certificado              :string
#  afip_clave                    :string
#  afip_certificado_homologacion :string
#  afip_clave_homologacion       :string
#  service_wsfe                  :boolean          default(FALSE), not null
#  service_padron                :boolean          default(FALSE), not null
#  puntos_de_venta               :json             not null
#  created_at                    :datetime         not null
#  updated_at                    :datetime         not null
#

require 'afiper/application_record'

module Afiper
  # Datos del contribuyente y claves para acceder a la API de la AFIP
  class Contribuyente < ApplicationRecord
    has_many :comprobantes, class_name: 'Afiper::Comprobante', foreign_key: :afiper_contribuyente_id

    validates :razon_social, :cuit, :iibb, :inicio_actividades, presence: true
    enum condicion_iva: { iva_responsable_inscripto: 0, monotributo: 1 }

    def self.for_wsfe
      where(service_wsfe: true).first
    end

    def self.for_padron
      where(service_padron: true).first
    end

    def wsfe_client
      if Afiper.configuration.wsfe_homologacion
        WsfeClient.new(cuit, afip_clave_homologacion, afip_certificado_homologacion)
      else
        WsfeClient.new(cuit, afip_clave, afip_certificado)
      end
    end

    def wsfex_client
      if Afiper.configuration.wsfe_homologacion
        WsfexClient.new(cuit, afip_clave_homologacion, afip_certificado_homologacion)
      else
        WsfexClient.new(cuit, afip_clave, afip_certificado)
      end
    end

    def padron_client
      if Afiper.configuration.padron_homologacion
        PadronClient.new(cuit, afip_clave_homologacion, afip_certificado_homologacion)
      else
        PadronClient.new(cuit, afip_clave, afip_certificado)
      end
    end

    def default_punto_de_venta(tipo)
      puntos_de_venta[tipo]
    end

    def proximo_numero(tipo, punto_de_venta)
      if Rails.env.test? && Comprobante.find_config(:nombre, tipo)[:codigo_afip].present?
        proximo_numero_segun_afip(tipo, punto_de_venta)
      else
        # wsfe_client.ultimo_cmp(tipo, punto_de_venta) + 1
        last = comprobantes.where(tipo: tipo, punto_de_venta: punto_de_venta).order(:numero).last
        (last.try(:numero) || 0) + 1
      end
    end

    def proximo_numero_segun_afip(tipo, punto_de_venta)
      if Comprobante.find_config(:nombre, tipo)[:exportacion]
        (wsfex_client.fex_get_last_cmp(tipo, punto_de_venta) || 0) + 1
      else
        (wsfe_client.ultimo_cmp(tipo, punto_de_venta) || 0) + 1
      end
    end

    def tipos_de_comprobante_que_emite
      Comprobante.configuracion_tipos.select do |t|
        t[:nombre].in?(%i[factura_a nota_de_credito_a nota_de_debito_a
                          factura_b nota_de_credito_b nota_de_debito_b
                          ticket_no_fiscal devolucion_no_fiscal
                          factura_e nota_de_credito_e nota_de_debito_e])
      end
    end

    def tipos_monotributo
      Comprobante.configuracion_tipos.select do |t|
        t[:nombre].in?(%i[factura_c nota_de_credito_c nota_de_debito_c
                          ticket_no_fiscal devolucion_no_fiscal
                          factura_e nota_de_credito_e nota_de_debito_e])
      end
    end

    def afip_configured?(homologacion)
      if homologacion
        afip_certificado_homologacion.present? && afip_clave_homologacion.present?
      else
        afip_certificado.present? && afip_clave.present?
      end
    end
  end
end

app/models/afiper/wsaa_token.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: afiper_wsaa_tokens
#
#  id                      :bigint           not null, primary key
#  afiper_contribuyente_id :bigint           not null
#  token                   :string           not null
#  sign                    :string           not null
#  cuit                    :string           not null
#  service                 :string           not null
#  homologacion            :boolean          not null
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#

require 'afiper/application_record'

module Afiper
  # Token para pegarle a la API de la AFIP
  class WsaaToken < ApplicationRecord
    def auth_hash_wsfe
      { Token: token, Sign: sign, Cuit: cuit }
    end

    def auth_hash_padron
      { token: token, sign: sign, cuitRepresentada: cuit }
    end
  end
end

app/controllers/afiper/application_controller.rb
# frozen_string_literal: true

module Afiper
  class ApplicationController < ::ApplicationController
    protect_from_forgery with: :exception
  end
end

app/controllers/afiper/contribuyentes_controller.rb
# frozen_string_literal: true
require 'afiper/application_controller'

module Afiper
  class ContribuyentesController < ApplicationController
    before_action :set_contribuyente, only: %i[show edit update destroy]

    def index
      @contribuyentes = Contribuyente.order(:id)
    end

    def new
      @contribuyente = Contribuyente.new
    end

    def create
      @contribuyente = Contribuyente.new(contribuyente_params)
      respond_to do |format|
        if @contribuyente.save
          format.html { redirect_to contribuyentes_path, notice: 'contribuyente was successfully created.' }
          format.json { render action: 'show', status: :created, location: @contribuyente }
        else
          format.html { render action: 'new' }
          format.json { render json: @contribuyente.errors, status: :unprocessable_entity }
        end
      end
    end

    def update
      respond_to do |format|
        @contribuyente.puntos_de_venta = params.require(:puntos_de_venta)
        @contribuyente.save
        if @contribuyente.update(contribuyente_params)
          format.html { redirect_to contribuyentes_path, notice: 'contribuyente was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @contribuyente.errors, status: :unprocessable_entity }
        end
      end
    end

    def destroy
      @contribuyente.destroy
      respond_to do |format|
        format.html { go_back }
        format.json { head :no_content }
      end
    end

    def edit; end

    def show; end

    private

      def set_contribuyente
        @contribuyente = Contribuyente.find(params[:id])
      end

      def contribuyente_params
        params.require(:contribuyente).permit(:razon_social, :cuit, :iibb, :inicio_actividades, :condicion_iva, :domicilio, :service_wsfe, :service_padron, :afip_certificado, :afip_clave, :afip_certificado_homologacion, :afip_clave_homologacion)
      end
  end
end

app/views/afiper/contribuyentes/_form.html.slim
.form-wrapper-small
  = form_for(@contribuyente, html: { class: "form-horizontal", role: "form" }) do |f|
    - if @contribuyente.errors.any?
      .alert.alert-danger.alert-dismissable role="alert"
        button.close type="button" data-dismiss="alert"
          span aria-hidden="true"
            | &times;
          span.sr-only
            | Close
        h4= "#{pluralize(@contribuyente.errors.count,"error")} prohibited this contribuyente from being saved:"
        ul
          - @contribuyente.errors.full_messages.each do |msg|
            li= msg
    h2 Datos principales
    .form-group
      = f.label :razon_social, class: "col-sm-4 control-label"
      .col-sm-8
        = f.text_field :razon_social, class: "form-control", required: true
    .form-group
      = f.label :cuit, 'CUIT', class: "col-sm-4 control-label"
      .col-sm-8
        = f.text_field :cuit, class: "form-control", style: "max-width: 130px", required: true
    .form-group
      = f.label :iibb, 'Ingresos brutos', class: "col-sm-4 control-label"
      .col-sm-8
        = f.text_field :iibb, class: "form-control", style: "max-width: 130px", required: true
    .form-group
      = f.label :domicilio, 'Domicilio', class: "col-sm-4 control-label"
      .col-sm-8
        = f.text_field :domicilio, class: "form-control", required: true
    .form-group
      = f.label :condicion_iva, 'Condición IVA', class: "col-sm-4 control-label"
      .col-sm-8
        = f.select :condicion_iva, options_for_select(Afiper::Contribuyente.condicion_ivas.map { |k,v| [k.titleize, k] }, f.object.condicion_iva), { include_blank: '-'}, class: 'form-control', style: "max-width: 230px", required: true
    .form-group
      = f.label :inicio_actividades, class: "col-sm-4 control-label"
      .col-sm-8
        = f.text_field :inicio_actividades, value: dmy(f.object.inicio_actividades), class: "datefield form-control", style: "max-width: 120px", required: true
    .form-group
      = f.label :service_wsfe, class: "col-sm-4 control-label"
      .col-sm-8
        = f.check_box :service_wsfe, class: "form-control"
    .form-group
      = f.label :service_padron, class: "col-sm-4 control-label"
      .col-sm-8
        = f.check_box :service_padron, class: "form-control"
    .form-group
      = f.label :afip_certificado, class: "col-sm-4 control-label"
      .col-sm-8
        = f.text_area :afip_certificado, class: "form-control"
    .form-group
      = f.label :afip_clave, class: "col-sm-4 control-label"
      .col-sm-8
        = f.text_area :afip_clave, class: "form-control"
    .form-group
      = f.label :afip_certificado_homologacion, class: "col-sm-4 control-label"
      .col-sm-8
        = f.text_area :afip_certificado_homologacion, class: "form-control"
    .form-group
      = f.label :afip_clave_homologacion, class: "col-sm-4 control-label"
      .col-sm-8
        = f.text_area :afip_clave_homologacion, class: "form-control"

    h2 Puntos de venta
    - @contribuyente.tipos_de_comprobante_que_emite.each do |tipo|
      .form-group
        = f.label nil, tipo[:descripcion], class: "col-sm-4 control-label"
        .col-sm-8
          = text_field_tag "puntos_de_venta[#{tipo[:nombre]}]", @contribuyente.puntos_de_venta[tipo[:nombre].to_s], class: "form-control", style: "max-width: 130px"
    .form-group
      .col-sm-offset-4.col-sm-8
        = f.submit class: "btn btn-primary"

javascript:
  $('form').validate();

app/views/afiper/contribuyentes/edit.html.slim
- content_for(:title, 'Editar contribuyente')
- content_for :actions do
  = link_to contribuyente_path(@contribuyente), class: 'btn btn-default' do 
    span.glyphicon.glyphicon-info-sign
    |  Ver 
  = link_to contribuyentes_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Listado 

= render 'form'

app/views/afiper/contribuyentes/index.html.slim
- content_for(:title, 'Contribuyentes')
- content_for :actions do
  = link_to new_contribuyente_path, class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-plus
    |  Nuevo contribuyente
table.table.table-bordered.table-striped.table-condensed
  tr
    th Razón social
    th CUIT
    th Ingresos brutos
    th Inicio de actividades
    th WSFE
    th Padrón
    th Acciones
  - @contribuyentes.each do |contribuyente|
    tr
      td = contribuyente.razon_social
      td = contribuyente.cuit
      td = contribuyente.iibb
      td = dmy contribuyente.inicio_actividades
      td = contribuyente.service_wsfe? ? 'SI' : '-'
      td = contribuyente.service_padron? ? 'SI' : '-'
      td
        span rel="tooltip" title="Ver"
          = link_to contribuyente, class: 'btn btn-xs btn-primary' do
            span.glyphicon.glyphicon-eye-open
        | &nbsp;
        span rel="tooltip" title="Editar"
          = link_to edit_contribuyente_path(contribuyente), class: 'btn btn-xs btn-default' do
            span.glyphicon.glyphicon-edit
        | &nbsp;
        span rel="tooltip" title="Borrar"
          = link_to contribuyente, data: {confirm: '¿Estás seguro?'}, method: :delete, class: 'btn btn-xs btn-danger' do
            span.glyphicon.glyphicon-trash

app/views/afiper/contribuyentes/new.html.slim
- content_for(:title, 'Nuevo contribuyente')
- content_for :actions do
  = link_to contribuyentes_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Volver 

= render 'form'

app/views/afiper/contribuyentes/show.html.slim
- content_for(:title, @contribuyente.razon_social)
- content_for :actions do
  = link_to contribuyentes_path, class: 'btn btn-default' do 
    span.glyphicon.glyphicon-list-alt
    |  Volver 
  = link_to edit_contribuyente_path(@contribuyente), class: 'btn btn-primary' do 
    span.glyphicon.glyphicon-pencil
    |  Editar 

dl.dl-horizontal
  dt Razón social:
  dd = @contribuyente.razon_social
  dt CUIT:
  dd = @contribuyente.cuit
  dt Ingresos brutos:
  dd = @contribuyente.iibb
  dt Inicio de actividades:
  dd = dmy @contribuyente.inicio_actividades
.row
  .col-sm-6
    h3 AFIP - Certificado:
    = text_area_tag nil, @contribuyente.afip_certificado, class: 'form-control', disabled: true, rows: 9
  .col-sm-6
    h3 AFIP - Clave:
    = text_area_tag nil, @contribuyente.afip_clave, class: 'form-control', disabled: true, rows: 9
.row
  .col-sm-6
    h3 AFIP - Certificado homologación:
    = text_area_tag nil, @contribuyente.afip_certificado_homologacion, class: 'form-control', disabled: true, rows: 9
  .col-sm-6
    h3 AFIP - Clave homologación:
    = text_area_tag nil, @contribuyente.afip_clave_homologacion, class: 'form-control', disabled: true, rows: 9